<?php

/**
 * @file
 * Contains user_detail.module
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */

function user_detail_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    // Main module help for the user_detail module.
    case 'help.page.user_detail':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom module that return a json response of users') . '</p>';
      return $output;
    break;
  }
}


/**
 * Implements hook_theme().
 */

function user_detail_theme()
{
  $theme = [];

  return $theme;
}
